### PR TITLE
feat(create): also set the app name in app.json

### LINKED ISSUE #231: app.json should be updated based on the input name.

### PR DESCRIPTION
**Pull request by zetavg**
Resolves #231

### CODE REVIEW

**Comment by zetavg** [comment]
I think we can merge this first, as it's already an improvement anyway.

**Comment by prabirshrestha** [comment]
Does vite.config.ts app.key also need to be updated?

**Comment by natew** [comment]
@zetavg the key should be updated yea.

Likely we can also leave out the key for expo when it detects an app.json it can just use that value directly.

**Comment by zetavg** [comment]
But surprisingly, if I change the `app.key` to a random value, the app still works, both on Expo Go and the built dev container.

I checked the [code](https://github.com/onejs/one/blob/v1.1.330/packages/one/src/createApp.native.tsx#L13) and noticed that it's possible that `app.key` isn't being used, and instead it'll be `'main'` all the time.

```tsx
export function createApp(options: CreateAppProps): void {
  const App = () => <Root isClient routes={options.routes} path="/" />

  AppRegistry.registerComponent('main', () => App)

  if (process.env.ONE_APP_NAME) {
    AppRegistry.registerComponent(process.env.ONE_APP_NAME, () => App)
  }
}
```

**Pull request merged**
